sudo: false
language: python
cache:
  directories:
    - "$HOME/.cache/pip"
env:
  - DEBUG=1
python:
  - "3.5"
install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements.txt
script:
  - flake8 tallessa
  - isort -c -rc tallessa
