# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tallessa_tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'stuff',
                'verbose_name': 'item',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tallessa_tenants.Tenant')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallessa_stuff.Location'),
        ),
        migrations.AddField(
            model_name='item',
            name='home_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_current_location_for_items', to='tallessa_stuff.Location'),
        ),
        migrations.AddField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='tallessa_stuff.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stuff', to='tallessa_tenants.Tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('tenant', 'slug')]),
        ),
        migrations.AlterIndexTogether(
            name='item',
            index_together=set([('tenant', 'serial_number')]),
        ),
    ]
