# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=511, unique=True)),
                ('admin_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_admin_group_for_teams', to='auth.Group')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_user_group_for_teams', to='auth.Group')),
            ],
        ),
    ]
